--PROLINGO_SUBJECT					
DROP TABLE	PROLINGO_SUBJECT	;			
CREATE TABLE	PROLINGO_SUBJECT	(			
SUBJECT_ID	NUMBER	PRIMARY KEY		,	--과목 아이디(직접 넣기)
SUBJECT_NAME	VARCHAR2(20)	NOT NULL		);	--과목 이름
					
--USER_SUBJECT					
DROP TABLE	USER_SUBJECT	;			
CREATE TABLE	USER_SUBJECT	(			--유저의 관심 과목
USER_ID	NUMBER	REFERENCES PROLINGO_USER(USER_ID)	ON DELETE CASCADE	,	--멤버 아이디
SUBJECT_ID	NUMBER	REFERENCES PROLINGO_SUBJECT(SUBJECT_ID)	ON DELETE CASCADE	,	--과목 아이디
PRIMARY KEY(USER_ID, SUBJECT_ID)				);	--복합키
					
--PROLINGO_LESSON					
DROP TABLE	PROLINGO_LESSON	;			
CREATE TABLE	PROLINGO_LESSON	(			
LESSON_ID	NUMBER	PRIMARY KEY		,	--학습 아이디(직접?)
SUBJECT_ID	NUMBER	REFERENCES PROLINGO_SUBJECT(SUBJECT_ID)	ON DELETE CASCADE	,	--과목 아이디
GRADE	VARCHAR2(20)	CHECK(GRADE IN('INTRODUTION', 'BEGINNER'))	NOT NULL	,	--과정 등급
LESSON_CONTENTS	VARCHAR2(2000)		NOT NULL	);	-- 레슨의 이름


-- PROLINGO_CONTENTS 개념 슬라이드 파트를 위한 테이블
DROP TABLE PROLINGO_CONTENTS; 
CREATE TABLE PROLINGO_CONTENTS(
    CONTENT_ID NUMBER PRIMARY KEY,                              -- 개념 식별 아이디 (seq로 nextval값을 넣을 예정, 슬라이드 정렬을 하는 기준)
    LESSON_ID	NUMBER	REFERENCES PROLINGO_LESSON(LESSON_ID),	-- 학습 아이디(학습페이지 식별을 위해서 사용, 슬라이드를 조회시 기준이 되기도 함)
    LESSON_TITLE VARCHAR2(100),                                 -- 해당 학습의 제목(ex. '시작하기')
    LESSON_SLIDE NUMBER,                                        -- 슬라이드의 번호
    LESSON_SUBTITLE VARCHAR2(200),                              -- 해당 슬라이드의 소제목(ex. 시작하기 - '코드 작성을 배워봅시다.')
    LESSON_CONTENTS	VARCHAR2(2000),                             -- 해당 슬라이드의 내용
    LESSON_PICTURE VARCHAR2(500)                                -- 사진 경로
);
-- CONTENT_ID의 생성을 위한 시퀀스
DROP SEQUENCE	PROLINGO_CONTENTS_SEQ;	
CREATE SEQUENCE	PROLINGO_CONTENTS_SEQ;	


--PROLINGO_QUESTION					
DROP TABLE	PROLINGO_QUESTION	;			
CREATE TABLE	PROLINGO_QUESTION	(			
QUESTION_ID	NUMBER	PRIMARY KEY		,	--문제 아이디
LESSON_ID	NUMBER	REFERENCES PROLINGO_LESSON(LESSON_ID)	ON DELETE CASCADE	,	--학습 아이디
QUESTION_CONTENTS	VARCHAR2(2000)		NOT NULL	,	--문제 내용
ANSWER	VARCHAR2(2000)			,	--정답(콘솔 출력 내용 객관식에서는 직접 만들기?)
KEYWORDS	VARCHAR2(1000)			);	--채점 할 때 들어가 있어야 하는 문구(객관식에선 문제로 만드는용도)

ALTER TABLE PROLINGO_QUESTION ADD DEFAULT_CODE VARCHAR2(2000);
ALTER TABLE PROLINGO_QUESTION ADD CONSOLE_RESULT VARCHAR2(1000);
					
--PROLINGO_KEYWORD					
DROP TABLE	PROLINGO_KEYWORD	;			
CREATE TABLE	PROLINGO_KEYWORD	(			--키워드의 정보만 가지고 있고 다른 테이블이랑 관계 없는듯
KEYWORD_ID	NUMBER	PRIMARY KEY		,	--키워드 아이디
KEYWORD_NAME	VARCHAR2(20)		NOT NULL	,	--키워드 이름(FOR, WHILE 등)
KEYWORD_TYPE	VARCHAR2(20)		NOT NULL	);	--키워드 타입(반복문, 제어문 등)
					
--PROLINGO_HISTORY					
DROP TABLE	PROLINGO_HISTORY	;			
CREATE TABLE	PROLINGO_HISTORY	(			
HISTORY_ID	NUMBER	PRIMARY KEY		,	--풀이 내역 아이디
USER_ID	NUMBER	REFERENCES PROLINGO_USER(USER_ID)	ON DELETE CASCADE	,	--멤버 아이디
QUESTION_ID	NUMBER	REFERENCES PROLINGO_QUESTION(QUESTION_ID)	ON DELETE CASCADE	,	--문제 아이디
HISTORY_CONTENT	VARCHAR2(2000)		NOT NULL	);	--풀이 내용
				
--PROLINGO_HISTORY_SEQ					
DROP SEQUENCE	PROLINGO_HISTORY_SEQ	;			
CREATE SEQUENCE	PROLINGO_HISTORY_SEQ	;		

COMMIT;