--PROLINGO_USER						
DROP TABLE	PROLINGO_USER	;				
CREATE TABLE	PROLINGO_USER				(	
USER_ID	NUMBER	PRIMARY KEY			,	--멤버 아이디
USER_PW	NUMBER	NOT NULL			,	--비밀번호
DEFAULAT_EMAIL	VARCHAR2(50)	NOT NULL	UNIQUE		,	--최초 가입 이메일
EMAIL	VARCHAR2(50)	NOT NULL	UNIQUE		,	--로그인에 사용할 이메일
USER_NAME	VARCHAR2(30)	NOT NULL			,	--이름
NICKNAME	VARCHAR2(30)	NOT NULL			,	--닉네임
PHOTO	VARCHAR2(100)				,	--프로필 사진
AGE	NUMBER				,	--나이
USER_ROLE	VARCHAR2(10)	DEFAULT 'NORMAL'	NOT NULL	CHECK(USER_ROLE IN('NORMAL', 'PLUS', 'ADMIN'))	,	--회원 등급
LOGINTYPE	VARCHAR2(10)	DEFAULT 'NORMAL' 	NOT NULL	CHECK(LOGINTYPE IN('NORMAL', 'GOOGLE', 'KAKAO', 'NAVER', 'FACEBOOK'))	,	--로그인 타입
JOINDATE	DATE	DEFAULT SYSDATE	NOT NULL		,	--가입일
EXP	NUMBER	DEFAULT 0	NOT NULL		,	--누적 경험치
CONTINUEDAY	NUMBER	DEFAULT 0	NOT NULL		,	--연속 학습일
MONEY	NUMBER	DEFAULT 0	NOT NULL		,	--재화
GOAL	NUMBER	DEFAULT 60	NOT NULL	CHECK(GOAL IN(20, 40, 60, 80, 100))	,	--일일 학습 목표
NOTICE	NUMBER	DEFAULT 0	NOT NULL	CHECK(NOTICE IN(0, 1))	,	--알림 설정
AUTOSAVE	NUMBER	DEFAULT 0	NOT NULL	CHECK(AUTOSAVE IN(0, 1)),	--해답 자동 저장
ACCURE_DATE NUMBER DEFAULT 0,          -- 누적 학습 일수
LAST_LOGIN DATE default '00/01/01'	);	-- 최종 로그인 일자 

COMMIT;
	
--PROLINGO_USER_SEQUENCE						
DROP SEQUENCE	PROLINGO_USER_SEQ	;				-- FOR USER_ID
CREATE SEQUENCE	PROLINGO_USER_SEQ	;				
						
--USER_FOLLOW						
DROP TABLE	USER_FOLLOW	;				
CREATE TABLE	USER_FOLLOW	(				
USER_ID	NUMBER	REFERENCES PROLINGO_USER(USER_ID)	ON DELETE CASCADE	,	--멤버 아이디	
TARGET_ID	NUMBER	REFERENCES PROLINGO_USER(USER_ID)	ON DELETE CASCADE	,	--팔로우 대상 아이디	
PRIMARY KEY(USER_ID, TARGET_ID)				);	--복합키	

insert into USER_FOLLOW
(USER_ID, TARGET_ID)
values
(30, 31);

insert into USER_FOLLOW
(USER_ID, TARGET_ID)
values
(30, 32);

commit;		
			
--USER_WEEKLY_EXP						
DROP TABLE	USER_WEEKLY_EXP	;				
CREATE TABLE	USER_WEEKLY_EXP	(				
USER_ID	NUMBER	REFERENCES PROLINGO_USER(USER_ID)	ON DELETE CASCADE	PRIMARY KEY	,	--멤버 아이디
MON_EXP	NUMBER	DEFAULT 0	NOT NULL	,	--월	
TUE_EXP	NUMBER	DEFAULT 0	NOT NULL	,	--화	
WED_EXP	NUMBER	DEFAULT 0	NOT NULL	,	--수	
THU_EXP	NUMBER	DEFAULT 0	NOT NULL	,	--목	
FRI_EXP	NUMBER	DEFAULT 0	NOT NULL	,	--금	
SAT_EXP	NUMBER	DEFAULT 0	NOT NULL	,	--토	
SUN_EXP	NUMBER	DEFAULT 0	NOT NULL	);	--월	



-- 업적 및 업적 달성 테이블 변경
--PROLINGO_ACHIEVEMENT
DROP TABLE
CREATE TABLE
ACHIEVEMENT_ID
ACHIEVEMENT_NAME
ACHIEVEMENT_TEXT
ACHIEVEMENT_PICTURE VARCHAR2(200)   NOT NULL        -- 업적사진 경로(img/achievements 폴더 안의 사진)
);

DROP SEQUENCE
CREATE SEQUENCE

--USER_ACHIEVE
DROP TABLE
CREATE TABLE USER_ACHIEVE
USER_ID
ACHIEVEMENT_ID
ACHIEVEMENT_DATE    DATE DEFAULT SYSDATE,                           -- 업적달성 시간(달성하면 SYSDATE로 넣음)
PRIMARY KEY(USER_ID, ACHIEVEMENT_ID));




-- 업적 데이터

-- 가입
INSERT INTO PROLINGO_ACHIEVEMENT(
ACHIEVEMENT_ID, ACHIEVEMENT_NAME, ACHIEVEMENT_TEXT, ACHIEVEMENT_PICTURE
)
values
(
PROLINGO_ACHIEVEMENT_SEQ.nextval, '프로링고의 친구', '프로링고의 회원이 되어주셨네요!', '/prolingo/img/achievement/sign_up.png'
);

-- 2일 출석
INSERT INTO PROLINGO_ACHIEVEMENT(
ACHIEVEMENT_ID, ACHIEVEMENT_NAME, ACHIEVEMENT_TEXT, ACHIEVEMENT_PICTURE
)
values
(
PROLINGO_ACHIEVEMENT_SEQ.nextval, '두번째 만남', '내일도 와주실거죠?', '/prolingo/img/achievement/2days.png'
);

-- 5일 출석
INSERT INTO PROLINGO_ACHIEVEMENT(
ACHIEVEMENT_ID, ACHIEVEMENT_NAME, ACHIEVEMENT_TEXT, ACHIEVEMENT_PICTURE
)
values
(
PROLINGO_ACHIEVEMENT_SEQ.nextval, '5일 출석', '오늘도 와주셨네요', '/prolingo/img/achievement/5days.png'
);

-- 10일 출석
INSERT INTO PROLINGO_ACHIEVEMENT(
ACHIEVEMENT_ID, ACHIEVEMENT_NAME, ACHIEVEMENT_TEXT, ACHIEVEMENT_PICTURE
)
values
(
PROLINGO_ACHIEVEMENT_SEQ.nextval, '10일 출석', '이제는 가족이네요', '/prolingo/img/achievement/10days.png'
);

-- 30일 출석
INSERT INTO PROLINGO_ACHIEVEMENT(
ACHIEVEMENT_ID, ACHIEVEMENT_NAME, ACHIEVEMENT_TEXT, ACHIEVEMENT_PICTURE
)
values
(
PROLINGO_ACHIEVEMENT_SEQ.nextval, '30일 출석', '꾸준한 당신에게 CHEERS', '/prolingo/img/achievement/30days.png'
);

-- 90일 출석
INSERT INTO PROLINGO_ACHIEVEMENT(
ACHIEVEMENT_ID, ACHIEVEMENT_NAME, ACHIEVEMENT_TEXT, ACHIEVEMENT_PICTURE
)
values
(
PROLINGO_ACHIEVEMENT_SEQ.nextval, '90일 출석', '세달이나 출석하셨네요', '/prolingo/img/achievement/90days.png'
);

-- 300일 출석
INSERT INTO PROLINGO_ACHIEVEMENT(
ACHIEVEMENT_ID, ACHIEVEMENT_NAME, ACHIEVEMENT_TEXT, ACHIEVEMENT_PICTURE
)
values
(
PROLINGO_ACHIEVEMENT_SEQ.nextval, '300일의 전사', 'THIS IS PROLINGO!!!', '/prolingo/img/achievement/300days.png'
);

-- 코스 시작
INSERT INTO PROLINGO_ACHIEVEMENT(
ACHIEVEMENT_ID, ACHIEVEMENT_NAME, ACHIEVEMENT_TEXT, ACHIEVEMENT_PICTURE
)
values
(
PROLINGO_ACHIEVEMENT_SEQ.nextval, '시작이 반이다', '차근차근 시작해봅시다', '/prolingo/img/achievement/start_course.png'
);

-- 한번이라도 코스 완료
INSERT INTO PROLINGO_ACHIEVEMENT(
ACHIEVEMENT_ID, ACHIEVEMENT_NAME, ACHIEVEMENT_TEXT, ACHIEVEMENT_PICTURE
)
values
(
PROLINGO_ACHIEVEMENT_SEQ.nextval, '코스 완료', '처음으로 학습 코스를 끝내주셨군요', '/prolingo/img/achievement/course_end.png'
);

-- 모든 코스 완료
INSERT INTO PROLINGO_ACHIEVEMENT(
ACHIEVEMENT_ID, ACHIEVEMENT_NAME, ACHIEVEMENT_TEXT, ACHIEVEMENT_PICTURE
)
values
(
PROLINGO_ACHIEVEMENT_SEQ.nextval, '모든 코스 완료', '모든 코스를 끝내주셨네요', '/prolingo/img/achievement/every_course_end.png'
);

-- 친구가 5명이상
INSERT INTO PROLINGO_ACHIEVEMENT(
ACHIEVEMENT_ID, ACHIEVEMENT_NAME, ACHIEVEMENT_TEXT, ACHIEVEMENT_PICTURE
)
values
(
PROLINGO_ACHIEVEMENT_SEQ.nextval, '프로링고의 스타', '당신같은 인싸를 기다렸다우', '/prolingo/img/achievement/many_friend.png'
);

-- 결제시 업적 완료
INSERT INTO PROLINGO_ACHIEVEMENT(
ACHIEVEMENT_ID, ACHIEVEMENT_NAME, ACHIEVEMENT_TEXT, ACHIEVEMENT_PICTURE
)
values
(
PROLINGO_ACHIEVEMENT_SEQ.nextval, '우리들의 영웅', '당신의 도움이 필요합니다', '/prolingo/img/achievement/payment.png'
);

-- 프로필 사진 등록
INSERT INTO PROLINGO_ACHIEVEMENT(
ACHIEVEMENT_ID, ACHIEVEMENT_NAME, ACHIEVEMENT_TEXT, ACHIEVEMENT_PICTURE
)
values
(
PROLINGO_ACHIEVEMENT_SEQ.nextval, '당신만의 멋짐', '멋진 당신을 뽐내주세요', '/prolingo/img/achievement/profile.png'
);

-- 랭킹에 특정 등수 달성
INSERT INTO PROLINGO_ACHIEVEMENT(
ACHIEVEMENT_ID, ACHIEVEMENT_NAME, ACHIEVEMENT_TEXT, ACHIEVEMENT_PICTURE
)
values
(
PROLINGO_ACHIEVEMENT_SEQ.nextval, '경쟁 시작', '이제부터 시작입니다', '/prolingo/img/achievement/rank_in.png'
);

-- 랭킹 1위
INSERT INTO PROLINGO_ACHIEVEMENT(
ACHIEVEMENT_ID, ACHIEVEMENT_NAME, ACHIEVEMENT_TEXT, ACHIEVEMENT_PICTURE
)
values
(
PROLINGO_ACHIEVEMENT_SEQ.nextval, '챔피언', '프로링고의 왕은 당신입니다', '/prolingo/img/achievement/rank_no1.png'
);

-- 코딩 테스트(문제만 푸는 유형) 첫 문제 완료
INSERT INTO PROLINGO_ACHIEVEMENT(
ACHIEVEMENT_ID, ACHIEVEMENT_NAME, ACHIEVEMENT_TEXT, ACHIEVEMENT_PICTURE
)
values
(
PROLINGO_ACHIEVEMENT_SEQ.nextval, '테스트 초심자', '코딩테스트 첫 문제 완료', '/prolingo/img/achievement/test_start.png'
);

-- 코딩 테스트 완료
INSERT INTO PROLINGO_ACHIEVEMENT(
ACHIEVEMENT_ID, ACHIEVEMENT_NAME, ACHIEVEMENT_TEXT, ACHIEVEMENT_PICTURE
)
values
(
PROLINGO_ACHIEVEMENT_SEQ.nextval, '승자', '코딩 테스트 완료', '/prolingo/img/achievement/test_winnner.png'
);

commit;
